### ISSUE TITLE
Render Box 

### ISSUE THREAD

**Issue by SahSantoshh** [sarbagyastha/nepali_date_picker#1]
The following assertion was thrown during performLayout():
I/flutter ( 8768): RenderViewport does not support returning intrinsic dimensions.
I/flutter ( 8768): Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
I/flutter ( 8768): defeats the point of viewports being lazy.
I/flutter ( 8768): If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a
I/flutter ( 8768): RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), which achieves that
I/flutter ( 8768): effect without implementing the intrinsic dimension API.
......

Launching lib/main.dart on SM J400F in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
D/libGLESv2( 8768): STS_GLApi : DTS, ODTC are not allowed for Package : com.sochware.nagarpalika
D/ViewRootImpl@f75e912[MainActivity]( 8768): ViewPostIme pointer 0
D/ViewRootImpl@f75e912[MainActivity]( 8768): ViewPostIme pointer 1
I/flutter ( 8768): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8768): The following assertion was thrown during performLayout():
I/flutter ( 8768): RenderViewport does not support returning intrinsic dimensions.
I/flutter ( 8768): Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
I/flutter ( 8768): defeats the point of viewports being lazy.
I/flutter ( 8768): If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a
I/flutter ( 8768): RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), which achieves that
I/flutter ( 8768): effect without implementing the intrinsic dimension API.
I/flutter ( 8768):
I/flutter ( 8768): When the exception was thrown, this was the stack:
I/flutter ( 8768): #0      RenderViewportBase.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:299:9)
I/flutter ( 8768): #1      RenderViewportBase.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:309:6)
I/flutter ( 8768): #2      RenderViewportBase.computeMaxIntrinsicWidth (package:flutter/src/rendering/viewport.dart:321:12)
I/flutter ( 8768): #3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #6      RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #11     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #13     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #15     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #16     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #18     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #20     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #21     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #23     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #24     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #25     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #26     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #28     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #29     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #30     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #31     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #33     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #34     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #35     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #36     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #38     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #39     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #40     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #41     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #43     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #44     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #45     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #46     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #47     RenderFlex.computeMaxIntrinsicWidth.<anonymous closure> (package:flutter/src/rendering/flex.dart:575:60)
I/flutter ( 8768): #48     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:552:58)
I/flutter ( 8768): #49     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:572:12)
I/flutter ( 8768): #50     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #51     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #52     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #53     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:76:20)
I/flutter ( 8768): #55     RenderConstrainedBox.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:226:32)
I/flutter ( 8768): #56     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #57     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #58     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #59     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #60     RenderPadding.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:163:20)
I/flutter ( 8768): #61     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #62     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #63     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #64     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #65     RenderFlex.computeMaxIntrinsicWidth.<anonymous closure> (package:flutter/src/rendering/flex.dart:575:60)
I/flutter ( 8768): #66     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:552:58)
I/flutter ( 8768): #67     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:572:12)
I/flutter ( 8768): #68     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1099:23)
I/flutter ( 8768): #69     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
I/flutter ( 8768): #70     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1097:41)
I/flutter ( 8768): #71     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1281:12)
I/flutter ( 8768): #72     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:617:36)
I/flutter ( 8768): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #81     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter ( 8768): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #83     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
I/flutter ( 8768): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #85     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter ( 8768): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #87     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 8768): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #89     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:13)
I/flutter ( 8768): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #91     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 8768): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #97     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #99     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #101    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #103    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #105    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 8768): #106    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
I/flutter ( 8768): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 8768): #108    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8768): #109    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 8768): #110    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 8768): #111    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 8768): #112    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 8768): #113    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 8768): #114    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8768): #115    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 8768): #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 8768): #117    _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 8768): #118    _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 8768):
I/flutter ( 8768): The following RenderObject was being processed when the exception was fired:
I/flutter ( 8768):   RenderIntrinsicWidth#2cd5c relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):   creator: IntrinsicWidth ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter ( 8768):   _InkFeatures-[GlobalKey#18522 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter ( 8768):   CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ←
I/flutter ( 8768):   ⋯
I/flutter ( 8768):   parentData: <none> (can use size)
I/flutter ( 8768):   constraints: BoxConstraints(280.0<=w<=331.4, 0.0<=h<=659.4)
I/flutter ( 8768):   size: MISSING
I/flutter ( 8768):   stepWidth: null
I/flutter ( 8768):   stepHeight: null
I/flutter ( 8768): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 8768):   RenderFlex#ca7c7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):     RenderPadding#9a7b2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):       RenderConstrainedBox#709d3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):         RenderFlex#c11ea NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):           RenderDecoratedBox#7480b NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):           RenderRepaintBoundary#b9b72 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):     RenderPadding#38cd8 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):       RenderFlex#d7ee6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):         RenderPadding#b1eb7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):           RenderSemanticsAnnotations#34dcc NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):         RenderPadding#de50f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768):           RenderSemanticsAnnotations#c4d32 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8768): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8768): Another exception was thrown: RenderBox was not laid out: RenderIntrinsicWidth#2cd5c relayoutBoundary=up6 NEEDS-PAINT
I/flutter ( 8768): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#60bff relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 8768): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#6af86 relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 8768): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#d389e relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 8768): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#421e1 relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 8768): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 314 pos 12: 'child.hasSize': is not true.
I/flutter ( 8768): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#421e1 relayoutBoundary=up2
D/ViewRootImpl@f75e912[MainActivity]( 8768): MSG_WINDOW_FOCUS_CHANGED 1

**Comment by sarbagyastha** [comment]
@SahSantoshh can you show me, how you're implementing the package ? Since the exception occured just after building(without any interactions), the problem could be in your way of implementation.

**Comment by SahSantoshh** [comment]
```
RaisedButton(
                      onPressed: () {
                        NepaliDatePicker.showPicker(
                          context: context,
                          startYear: 2052,
                          endYear: 2085,
                          color: Colors.pink,
                          barrierDismissible: false,
                          language: Language.NEPALI,
                          onPicked: (DateTime date) {
                            setState(() {
                              ///Iso8601String Format: 2018-12-23T00:00:00
                              _pickedDate =
                                  date.toIso8601String().split("T").first;
                            });
                          },
                        );
                      },
                    ),
                    Text(_pickedDate.toString()),
```

**Comment by sarbagyastha** [comment]
@SahSantoshh , is the example running fine on your device ? [Example](https://github.com/sarbagyastha/nepali_date_picker/tree/master/example)

**Comment by SahSantoshh** [comment]
nope

**Comment by sarbagyastha** [comment]
@SahSantoshh same problem ?

**Comment by SahSantoshh** [comment]
yes
