### ISSUE TITLE
I'm getting this while just importing nepali_date_picker package.

### ISSUE THREAD

**Issue by codernirdesh** [sarbagyastha/nepali_date_picker#10]
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-1.0.pre.267, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1.0)
[✓] VS Code (version 1.56.0)
[✓] Connected device (3 available)
• No issues found!
Running "flutter pub get" in baigundhura_computer... 6.1s
Launching lib\main.dart on BE2013 in debug mode...
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_picker_dialog.dart:291:8: Error: A non-null value must be returned since the return type 'Size' doesn't allow null.
- 'Size' is from 'dart:ui'.
Size _dialogSize(BuildContext context) {
^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_picker_dialog.dart:447:24: Error: Final variable 'entryModeButton' must be assigned before it can be used.
entryModeButton: entryModeButton,
^^^^^^^^^^^^^^^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_picker_dialog.dart:470:39: Error: Non-nullable variable 'picker' must be assigned before it can be used.
Expanded(child: picker),
^^^^^^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_picker_dialog.dart:485:45: Error: Non-nullable variable 'picker' must be assigned before it can be used.
Expanded(child: picker),
^^^^^^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_range_picker_dialog.dart...: Error: Non-nullable variable 'size' must be assigned before it can be used.
width: size.width,
^^^^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_range_picker_dialog.dart...: Error: Non-nullable variable 'size' must be assigned before it can be used.
height: size.height,
^^^^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_range_picker_dialog.dart...: Error: Non-nullable variable 'contents' must be assigned before it can be used.
return contents;
^^^^^^^^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_range_picker_dialog.dart...: Error: Non-nullable variable 'insetPadding' must be assigned before it can be used.
insetPadding: insetPadding,
^^^^^^^^^^^^
/C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/http://pub.dartlang.org/.../date_range_picker_dialog.dart...: Error: Non-nullable variable 'elevation' must be assigned before it can be used.
elevation: elevation,
^^^^^^^^^
FAILURE: Build failed with an exception.
* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 57s
Running Gradle task 'assembleDebug'... 119.9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sarbagyastha** [comment]
Current master has some breaking change, will soon release a dev version with the fix.
