### ISSUE TITLE
How to pick time in Nepali Language?

### ISSUE THREAD

**Issue by 2shrestha22** [sarbagyastha/nepali_date_picker#13]
I didn't find any way to pick time in Nepali Language. Is it possible to do so?

**Comment by sarbagyastha** [comment]
You can do this to switch between languages. 
 https://github.com/sarbagyastha/nepali_date_picker/blob/0368448952e0b03eae9bd71a952851677209f94f/example/lib/main.dart#L55

**Comment by 2shrestha22** [comment]
@sarbagyastha it is already in Nepali, I am saying about calendar that pop ups when using date picker. Those calendar are in English like `Baisakh`, `Jestha`.

**Comment by sarbagyastha** [comment]
```dart
NepaliUtils().language = Language.nepali;
showMaterialDatePicker();
```
