### ISSUE TITLE
Blank date display

### ISSUE THREAD

**Issue by shresthaRam** [sarbagyastha/nepali_date_picker#3]
The nepali date picker display blank date. No any number date are display in the calender. Not every time but sometime.

**Comment by sarbagyastha** [comment]
Sorry for late response @shresthaRam . Could you please attach a log for the scenario ?

**Comment by shresthaRam** [comment]
Sorry for the late reply. Please find the attachment for screenshot that
the date are not displayed in calender.

Thank you for your help!!!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/12/19,
4:54:50 PM

**Comment by sarbagyastha** [comment]
@shresthaRam, couldn't receive attachments. Could you please mail me the attachments at `github@sarbagyastha.com.np`
