### ISSUE TITLE
Add function to calculate number of days between two nepali dates

### ISSUE THREAD

**Issue by igaurab** [sarbagyastha/nepali_date_picker#4]
Something like:
`nepaliCalender.duration( date1, date2)`

**Comment by sarbagyastha** [comment]
@igaurab You can do like this,

```dart
NepaliDateTime date1, date2;

Duration duration = date1.difference(date2);
int valueIndays = duration.inDays;
```
[Find more here](https://pub.dev/documentation/nepali_utils/latest/nepali_utils/NepaliDateTime-class.html)
