### ISSUE TITLE
Nepali font not showing and CalendarDatePicker widget Not working

### ISSUE THREAD

**Issue by godng73** [sarbagyastha/nepali_date_picker#7]
I want to show a calendar of Nepali font calendar which is not happenning even if i used language parameter in showAdaptiveDatePicker. 
`_selectedDateTime = await showAdaptiveDatePicker(
                  context: context,
                  initialDate: NepaliDateTime.now(),
                  firstDate: NepaliDateTime(2077),
                  lastDate: NepaliDateTime(2090),
                  language: Language.nepali,
                  initialDatePickerMode: DatePickerMode.day,
                );`

Also I want to use calendar in the main display not in a picker(popup) form. For this I used CalendarDatePicker widget which cannot be used. 
Am I doing wrong or ?
`Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CalendarDatePicker(
              initialDate: NepaliDateTime.now(),
              firstDate: NepaliDateTime(2070),
              lastDate: NepaliDateTime(2090),
              onDateChanged: (date) => _selectedDate.value = date,
              dayBuilder: (dayToBuild) { // Optional
                return Center(
                  child: Text(
                    '${dayToBuild.day}',
                    style: Theme
                        .of(context)
                        .textTheme
                        .caption,
                  ),
                );
              },
              selectedDayDecoration: BoxDecoration( // Optional
                color: Colors.deepOrange,
                shape: BoxShape.circle,
              ),
              todayDecoration: BoxDecoration( // Optional
                gradient: LinearGradient(
                    colors: [Colors.yellow, Colors.orange]),
                shape: BoxShape.circle,
              ),
            ),
          ],
        ),`

**Comment by sarbagyastha** [comment]
> I want to show a calendar of Nepali font calendar which is not happenning even if i used language parameter in showAdaptiveDatePicker.

You can change language like this: `NepaliUtils().language = Language.nepali;` , before calling showAdaptiveDatePicker

> Also I want to use calendar in the main display not in a picker(popup) form. For this I used CalendarDatePicker widget which cannot be used.
Am I doing wrong or ?

Just hide `CalendarDatePicker` from material, or you can add prefix to nepali-date_picker library
![image](https://user-images.githubusercontent.com/9782008/93870384-e0aae900-fcec-11ea-94d4-37ccc76f0433.png)

**Comment by TAMU73** [comment]
Thank You for the answer.
And how can we change the language in CalendarDatePicker widget? I tried using util package in it but it is only changing the weeks and month name not the date numbers?

**Comment by TAMU73** [comment]
How to change the colouring and text style for the text in weeks, months name and date numbers??
Please provide detailed documentation.
