### ISSUE TITLE
CalendarDatePicker in Nepali language

### ISSUE THREAD

**Issue by godng73** [sarbagyastha/nepali_date_picker#8]
How can we change the language in #CalendarDatePicker widget? I tried using util package in initstate but it is only changing the weeks and month name not the date numbers?

![image](https://user-images.githubusercontent.com/47109205/94109169-4e2b5680-fe60-11ea-9a09-ef00f1ff06ee.png)
`
  void initState() {
    // TODO: implement initState
    super.initState();
    NepaliUtils().language = Language.nepali;
  }`

**Comment by sarbagyastha** [comment]
```dart
dayBuilder: (dayToBuild) {
      return Center(
                child: Text(
                   NepaliUnicode.convert(dayToBuild.day),
                    style: Theme.of(context).textTheme.caption,
               ),
          ),
      },
```
